# 100 numpy exercises

DEBER EDUARDO ALMACHI
Dentro del grupo asignado (2 o 3 estudiantes) realizar 50  ejercicios del archivo: Numpy - 100 Exercises.pdf

Entregables: .ipynb o (.py + capturas en pdf)



If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
#1
import numpy as np

#### 3. Create a null vector of size 10 (★☆☆)

In [1]:
#2
vector = np.zeros(10)
print(vector)

NameError: name 'np' is not defined

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [4]:
#3
import numpy as nop
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
#4
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
#5
vector = np.arange(10)
vector = vector[::-1]
print(vector)

[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
#6
matriz = np.arange(9).reshape(3,3)
print(matriz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [14]:
#7
vectorbuscar = np.nonzero([1,2,0,0,4,0])
print(vectorbuscar)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [15]:
#8
matriziden = np.eye(3)
print(matriziden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [17]:
#9
matriz = np.random.random((3, 3, 3))
print(matriz)

[[[0.29008441 0.08979533 0.78836058]
  [0.29497024 0.51472685 0.60615964]
  [0.86993231 0.79967685 0.57466436]]

 [[0.33786788 0.37058408 0.39147527]
  [0.3762985  0.11614583 0.84985444]
  [0.56182676 0.46471341 0.34064707]]

 [[0.00211704 0.73736178 0.07936475]
  [0.57397359 0.72328948 0.43511473]
  [0.93293645 0.37384806 0.75989807]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [22]:
#10
matriz = np.random.random((10, 10))
print(matriz)
matrizMin, matrizMax = matriz.min(), matriz.max()
print("min: ", matrizMin,"max: ", matrizMax)

[[0.04605565 0.22073018 0.45577064 0.00786071 0.95796379 0.18201139
  0.08165901 0.57373658 0.51352996 0.94336768]
 [0.90383977 0.50165487 0.66857956 0.18034905 0.13197727 0.67202104
  0.70294605 0.26008592 0.40432788 0.9153486 ]
 [0.4787808  0.60344149 0.79373682 0.05768437 0.01276696 0.73529504
  0.06652742 0.15785771 0.85289602 0.83125737]
 [0.0362807  0.20030801 0.01636488 0.67753747 0.20820566 0.73641542
  0.30954643 0.84450591 0.7885863  0.31522239]
 [0.2796963  0.38030438 0.1067468  0.14699562 0.02507646 0.44558475
  0.72286904 0.16769865 0.68978573 0.38267821]
 [0.64968619 0.58808424 0.11382078 0.70867627 0.97888837 0.84581517
  0.42050487 0.22496858 0.62530428 0.14149871]
 [0.24080195 0.47483534 0.62583224 0.00215804 0.92819671 0.56663761
  0.12317194 0.92353445 0.38105013 0.58624418]
 [0.50142734 0.64801009 0.10252035 0.05145962 0.22908659 0.78700789
  0.44418242 0.83889754 0.95269087 0.52436435]
 [0.68948434 0.22871114 0.12810348 0.75640359 0.69763965 0.58984152
  0.61721794

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [25]:
#11
vector = np.random.random(10)
print(vector)
media = vector.mean()
print("\n", media)

[0.17730706 0.27999659 0.30091014 0.04309022 0.16352569 0.64948159
 0.19179091 0.44846122 0.07804633 0.5553749 ]

 0.2887984665650456


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [26]:
#12
matriz = np.ones((10, 10))
matriz[1:-1, 1:-1] = 0
print(matriz)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [28]:
#13
vector = np.ones((5,5))
vector = np.pad(vector, pad_width=1, mode='constant', constant_values=0)
print(vector)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [29]:
#14
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [31]:
#15
matriz = np.diag(1 + np.arange(4), k = -1)
print(matriz)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [32]:
#16
matriz = np.zeros((8,8),dtype=int)
matriz[1::2,::2] = 1
matriz[::2,1::2] = 1
print(matriz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [35]:
#17
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [36]:
#18
matriz = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(matriz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [37]:
#18
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.87905468 0.69944891 0.427902   0.49413171 0.01480645]
 [0.73305631 0.41430237 0.6955836  0.16170715 0.78004936]
 [0.06441612 0.20528861 0.50450859 0.82600253 0.87682777]
 [0.         0.06620646 0.0538219  0.3634041  0.77817894]
 [0.8924164  1.         0.2491585  0.15284984 0.1100835 ]]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [41]:
#19
vector = np.dot(np.ones((5,3)), np.ones((3,2)))
print(vector)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

'''print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
'''

In [ ]:
#20
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [40]:
#21
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 29. How to round away from zero a float array ? (★☆☆)

In [44]:
#22
vector = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(vector)), vector))

[  3.   2.   9.  -2.  -9. -10.  -9.   3.  -7.   9.]


#### 30. How to find common values between two arrays? (★☆☆)

In [48]:
#23
vector1 = np.random.randint(0,10,10)
vector2 = np.random.randint(0,10,10)
print(vector1)
print(vector2)
print("\n", np.intersect1d(vector1, vector2))

[2 1 3 8 1 0 0 9 1 3]
[6 4 6 5 4 5 5 5 7 9]

 [9]


#### 31. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [50]:
#24
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\eduar\AppData\Local\Temp\ipykernel_4072\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [3]:
#25
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2023-05-25
2023-05-26
2023-05-27


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [8]:
#26
matriz = np.zeros((5, 5))
matriz += np.arange(5)
print(matriz)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [9]:
#27
def generador():
    for x in range(10):
        yield x
vector = np.fromiter(generador(),dtype=float,count=-1)
print(vector)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [10]:
#28
vector = np.linspace(0,1,12,endpoint=True)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [11]:
#29
vector = np.random.random(10)
vector.sort()
print(vector)

[0.00771555 0.079385   0.11345299 0.33008176 0.45090748 0.49969838
 0.62541525 0.73849409 0.91282462 0.92142888]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [15]:
#30
vector = np.arange(10)
print(vector)
np.add.reduce(vector)


[0 1 2 3 4 5 6 7 8 9]


45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [21]:
#31
vector1 = np.random.randint(0, 2, 5)
vector2 = np.random.randint(0, 2, 5)
equal = np.array_equal(vector1, vector2)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [22]:
#32
vector = np.zeros(10)
vector.flags.writeable = False
vector[0] = 1

ValueError: assignment destination is read-only

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [26]:
#33
vector = np.random.random(10)
vector[vector.argmax()] = 0
print(vector)

[0.18854615 0.35966079 0.66217922 0.38760122 0.29766616 0.1815657
 0.00366063 0.23775911 0.         0.81378294]


#### 49. How to print all the values of an array? (★★☆)

In [28]:
#34
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [31]:
#35
vector = np.arange(10, dtype=np.int32)
vector = vector.astype(np.float32, copy=False)
print(vector)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [33]:
#36
vector = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(vector):
    print(index, value)
for index in np.ndindex(vector.shape):
    print(index, vector[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [36]:
#37
n = 10
p = 3
vector = np.zeros((n,n))
np.put(vector, np.random.choice(range(n*n), p, replace=False),1)
print(vector)

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [37]:
#38
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]


#### 59. How to sort an array by the nth column? (★★☆)

In [38]:
#39
vector = np.random.randint(0,10,(3,3))
print(vector)
print(vector[vector[:,1].argsort()])

[[0 9 6]
 [3 0 5]
 [3 2 7]]
[[3 0 5]
 [3 2 7]
 [0 9 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [39]:
#40
vector = np.random.randint(0,3,(3,10))
print((~vector.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [41]:
#41
vector = np.random.uniform(0,1,10)
valor = 0.5
m = vector.flat[np.abs(vector - valor).argmin()]
print(m)

0.5667087974941614


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [42]:
#42
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [43]:
#43
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[60 57 62 46]
 [34 36 63 45]
 [34 53 51 43]]


#### 69. How to get the diagonal of a dot product? (★★★)

In [44]:
#44
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
 
np.diag(np.dot(A, B))

array([1.69799416, 1.67842547, 1.55393878, 0.67185162, 1.44111144])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [47]:
#45
vector = np.array([1,2,3,4,5])
nz = 3
vector0 = np.zeros(len(vector) + (len(vector)-1)*(nz))
vector0[::nz+1] = vector
print(vector0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [48]:
#46
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [50]:
#47
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]

print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [51]:
#48
vector = np.random.randint(0,2,100)
np.logical_not(vector, out=vector)

vector = np.random.uniform(-1.0,1.0,100)
np.negative(vector, out= vector)

array([ 0.21955703,  0.14956674, -0.2700746 ,  0.23024611, -0.44101535,
        0.99010888,  0.49611912, -0.10147017, -0.6553003 ,  0.97312908,
       -0.32224113,  0.10403367,  0.15519725,  0.17414443,  0.60208511,
        0.08156861, -0.52335436,  0.26293817,  0.99745299, -0.65291628,
        0.89198607,  0.38178791, -0.68570409,  0.19544624,  0.36214152,
       -0.74866211,  0.06393645,  0.74410231,  0.56931086, -0.70383516,
       -0.88583806,  0.94566072, -0.41073754, -0.15274597, -0.63825396,
       -0.28828856,  0.22488465,  0.32025794, -0.14243213,  0.35640461,
       -0.02576167, -0.78825741,  0.37283263,  0.73828875,  0.98073936,
        0.6882079 ,  0.43618696,  0.66068237, -0.62979115,  0.48619531,
        0.34532029,  0.48949458,  0.6150091 ,  0.38364425, -0.3406898 ,
        0.39056611, -0.5436376 ,  0.66129119,  0.9963811 , -0.00387975,
       -0.39223226, -0.06818557,  0.27373445, -0.26633138,  0.2561443 ,
       -0.3279694 ,  0.29483156,  0.41968832,  0.74185117,  0.30

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [10]:
#49
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [29]:
#50
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.1769451   0.16715272]
