In [13]:
import time
import numpy as np
import sys

SIZE = 1000000

L1 = range(SIZE)
L2 = range(SIZE)
A1 = np.arange(SIZE)
A2 = np.arange(SIZE)
start = time.time()
result =[(x,y) for x,y in zip(L1,L2)] # Revisar Comprehension
print((time.time()-start)*1000)
start = time.time()
result = A1+A2
print((time.time()-start)*1000)

147.10569381713867
38.89584541320801


In [15]:
import time
import numpy as np

list1 = [i for i in range (1000)]
list2 = [i for i in range (1000)]

inicio = time.time()
dot = 0
for i,j in zip(list1, list2):
    dot += i *j
    
round(time.time()-inicio, 5)

0.0

In [17]:
import time
import numpy as np

import time
import numpy as np
arr1 = np.array([i for i in range(10000000)])
arr2 = np.array([i for i in range(10000000)])
inicio = time.time()
arr = np.dot(arr1, arr2)
round(time.time()-inicio,5)


0.012

0.0

0.001

In [20]:
#concatenacion de dos arreglos

In [21]:
import time
import numpy as np
arr1=np.array([i for i in range(10000)])
arr2=np.array([i for i in range(10000)])
inicio = time.time()
arr=np.concatenate((arr1,arr2),axis=0)
round(time.time()-inicio,5)

0.0

In [22]:
import time
import numpy as np
list1=[i for i in range (10000)]
list2=[i for i in range (10000)]
inicio = time.time()
list1+=list2
round(time.time()-inicio,5)

0.0

In [23]:
#Eliminación


In [24]:
import time
import numpy as np
list1=[i for i in range (10000)]
inicio = time.time()
del(list1)
round(time.time()-inicio,5)

0.0

In [25]:
import time
import numpy as np
arr1=np.array([i for i in range(10000)])
inicio = time.time()
del(arr1)
round(time.time()-inicio,5)

0.0

In [26]:
#Ejercicios

In [28]:
lista = [25, 12, 15, 66, 12.5] 
vector = np.array(lista) 
print(vector)

[25.  12.  15.  66.  12.5]


In [29]:
#al ser el elemento vector de numpy, 
#nos permite realizar operaciones de 
#forma simple

In [32]:
# Podemos acceder a sub elementos 
# del vector:
print(vector[3])
print(vector[1:4])
print(vector[1:])
print(vector[:4])
print(vector[:])

66.0
[12. 15. 66.]
[12.  15.  66.  12.5]
[25. 12. 15. 66.]
[25.  12.  15.  66.  12.5]


In [34]:
print("- vector original")
print(vector)
print("- sumarle 1 a cada elemento del vector:")
print(vector + 1)
print("- multiplicar por 5 cada elemento del vector:")
print(vector * 5)
print("- suma de los elementos:")
print(np.sum(vector))
print("- promedio (media) de los elementos:")
print(np.mean(vector)) # 
print("- el vector sumado a si mismo:")
print(vector + vector)
print("- suma de vectores vector1 y vector2 (mismo tamaño):")
vector2 = np.array([11,55,1.2,7.4,-8])
print(vector + vector2)

- vector original
[25.  12.  15.  66.  12.5]
- sumarle 1 a cada elemento del vector:
[26.  13.  16.  67.  13.5]
- multiplicar por 5 cada elemento del vector:
[125.   60.   75.  330.   62.5]
- suma de los elementos:
130.5
- promedio (media) de los elementos:
26.1
- el vector sumado a si mismo:
[ 50.  24.  30. 132.  25.]
- suma de vectores vector1 y vector2 (mismo tamaño):
[36.  67.  16.2 73.4  4.5]


In [35]:
#matrices


In [39]:
print("- Matriz creada con una lista de listas:")
lista_de_listas=[ [1 ,-4], 
                  [12 , 3], 
                  [7.2, 5]]

matriz = np.array(lista_de_listas)
print(matriz)

print("- Matriz creada con np.zeros:")
dimensiones=(2,3)
matriz_ceros = np.zeros(dimensiones)
print(matriz_ceros)

print("- Matriz creada con np.ones:")
dimensiones=(3,2)
matriz_unos = np.ones(dimensiones)
print(matriz_unos)

- Matriz creada con una lista de listas:
[[ 1.  -4. ]
 [12.   3. ]
 [ 7.2  5. ]]
- Matriz creada con np.zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
- Matriz creada con np.ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [41]:
#también podemos usar np.copy para copiar una matriz 
print("- Copia de la matriz creada con np.ones:")
matriz_unos_copia=np.copy(matriz_unos)
print(matriz_unos_copia)


- Copia de la matriz creada con np.ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [43]:
#ejercicios matrices


In [51]:
dimensiones=(4, 4)
matriz_unos = np.ones(dimensiones)

print(matriz_unos * 0.5)

[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [64]:
import random
 
random.randint(1, 101)
matriz = np.random.randint(1, 101, size = (5, 5))
print(matriz)

[[76 23 88 31 38]
 [28 51 34 75 78]
 [39 31  2 84 19]
 [96 87 83 39  9]
 [33 62 91 94 51]]


In [58]:
#ejercicios
# Ejercicios:
# Crear un vector con valores dentro del rango 10 a 49
a = np.arange(10,50)

In [59]:
a[::-1]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [60]:
# Crear una matriz 3x3 con valores de 0 a 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
# Crear una matriz identidad de 6x6
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [62]:
# Crear una matriz con valores al azar con forma 3x3x3
r = np.random.random((3,3,3))
r


array([[[0.11504137, 0.5154958 , 0.58252652],
        [0.23322876, 0.33698758, 0.44658036],
        [0.00995934, 0.54442635, 0.36969774]],

       [[0.28500384, 0.69682094, 0.01580549],
        [0.34525606, 0.63392236, 0.90045597],
        [0.08064305, 0.8568435 , 0.14207912]],

       [[0.92951903, 0.2231868 , 0.59020355],
        [0.42488288, 0.7911182 , 0.68461419],
        [0.04802913, 0.74151012, 0.19056559]]])

In [65]:
#Ejericicios


In [67]:
# Encontrar los indices de los valores minimos y maximos de la anterior matriz
print( r.argmax() )
print( r.ravel()[r.argmax()] )

print(r)
print(np.unravel_index(r.argmax(), r.shape))
r[np.unravel_index(r.argmax(), r.shape)]

18
0.9295190325101812
[[[0.11504137 0.5154958  0.58252652]
  [0.23322876 0.33698758 0.44658036]
  [0.00995934 0.54442635 0.36969774]]

 [[0.28500384 0.69682094 0.01580549]
  [0.34525606 0.63392236 0.90045597]
  [0.08064305 0.8568435  0.14207912]]

 [[0.92951903 0.2231868  0.59020355]
  [0.42488288 0.7911182  0.68461419]
  [0.04802913 0.74151012 0.19056559]]]
(2, 0, 0)


0.9295190325101812

In [70]:
# Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de indices)
z = np.ones((10,10))
z[1:-1,1:-1] = 0
z


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [71]:
#ejericicios


In [72]:
# Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4
np.tile( np.arange(0,5) , 5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [73]:
# Crear dos arreglos al azar A y B, verificar si son iguales
a = np.random.random((3,3))
b = np.random.random((3,3))
a == b


array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [91]:
#EJERCICIOS
# Tomar el tiempo de la multiplicación de matrices de las siguientes dimensiones:
# 10x10, 100x100, 1000x1000 
# Guardar los tiempos de los resultados en un archivo


inicio = time.time()
#10
matriz = np.random.randint(1, 100, size = (10, 10))
matriz_copia = np.copy(matriz) 
print(matriz * matriz_copia)

tiempo = round(time.time()-inicio, 5)
print("Tiempo trabajo: ", tiempo)
t = str(tiempo)

archivo = open("numpy.txt", "a")
archivo.write("\n" + t + "\n")
archivo.close()





[[1681    1 5476 1681   64  361  900 5625  196 3481]
 [ 169 1600 9604  900 3481  529 4489 2209 6084  121]
 [  49 7744 3481  961 1225 5041    1 8649  289  841]
 [3844   16 6241 9604 3025  361 9801 6241 2809    1]
 [ 196 1024 2304  961 4356  676 9216 4356 4624 1369]
 [  49 3721 1764 1089  196 4624 1225  121 9409  784]
 [7569  324 2809  900 8649  289 2025  324 3025  361]
 [ 576 5776 7225 1849  841  729 5476  529  225    9]
 [5476 8464  676 1024 7921 2500 2916 6889   49    4]
 [ 289   16   25 5776   16 8100 6241 4900   25  841]]
Tiempo trabajo:  0.0


In [90]:
inicio = time.time()
#100
matriz = np.random.randint(1, 100, size = (100, 100))
matriz_copia = np.copy(matriz) 
print(matriz * matriz_copia)

tiempo = round(time.time()-inicio, 5)
print("Tiempo trabajo: ", tiempo)
t = str(tiempo)

archivo = open("numpy.txt", "a")
archivo.write("\n" + t + "\n")
archivo.close()

[[1089  576 1024 ... 1600 7225 3600]
 [1444   49 9604 ... 1444   49 6084]
 [ 324 6084  400 ... 6561 8836  961]
 ...
 [4225 5041 1296 ... 1681 1936 1156]
 [9409  676 2704 ... 3844 9216 1156]
 [   1 2116 2401 ... 3025    9  289]]
Tiempo trabajo:  0.00102


In [92]:
inicio = time.time()
#100
matriz = np.random.randint(1, 100, size = (1000, 1000))
matriz_copia = np.copy(matriz) 
print(matriz * matriz_copia)

tiempo = round(time.time()-inicio, 5)
print("Tiempo trabajo: ", tiempo)
t = str(tiempo)

archivo = open("numpy.txt", "a")
archivo.write("\n" + t + "\n")
archivo.close()

[[   9   81 5929 ... 5776 2704 9409]
 [5041  529    9 ... 7921  144 1764]
 [3025   49 4356 ... 8836 4356 1521]
 ...
 [3721 2704 7744 ...  256  225 4900]
 [4900 8100  144 ... 2500 2916 8836]
 [3844 9604  676 ... 7056 3721   49]]
Tiempo trabajo:  0.01288


In [93]:
inicio = time.time()
#100
matriz = np.random.randint(1, 100, size = (10000, 10000))
matriz_copia = np.copy(matriz) 
print(matriz * matriz_copia)

tiempo = round(time.time()-inicio, 5)
print("Tiempo trabajo: ", tiempo)
t = str(tiempo)

archivo = open("numpy.txt", "a")
archivo.write("\n" + t + "\n")
archivo.close()

[[7056   16  169 ... 6400 6084 3969]
 [5929   25   64 ...  225   16    4]
 [  64 8100 2809 ... 2601 2601   64]
 ...
 [ 729 1089 9409 ... 1156 3364 8281]
 [ 289 1444 5329 ...  144 2401 2209]
 [   1 2916  324 ... 9216 3969 2601]]
Tiempo trabajo:  1.26511
